name: Elect
# this will help you specify where to run
on:
  push:
    branches:
      - master
jobs:
  build_on_win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 20.14
      - name: install node-gyp
        run: npm install --global node-gyp@latest
      - name: Work around for Windows Server 2019
        run: set path=%path%;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
      - name: Install dependencies
        run: npm install
      - name: check env
        env:
          ELECTRON: true
          APP_VERSION_NUMBER: 0.5.9
        run: set
      - name: Build on Windows
        env:
          ELECTRON: true
          APP_VERSION_NUMBER: 0.5.9
        run: npm run make
      - name: see directory
        run: ls ./out/make
